Oxy 46
FITER1/fineract-template pull request #38
Opened 2023-02-13 09:36 UTC by jumba2010

## Description

This feature will allow the user to create client tiers limits and to validate those limits when making operations like deposit or withdraw on savings account. The details can be seen on this ticket [https://fiterio.atlassian.net/browse/OXY-46](url) and this [https://fiterio.atlassian.net/browse/OXY-72](url)

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-02-13 19:07 UTC, Napho requested changes
Also dont forget to run spotlessApply before pushing changes

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/MON-110_Vault_Tribe.xml
> +            INSERT INTO m_permission (grouping, code, entity_name, action_name, can_maker_checker) VALUES ('transaction_savings', 'UNLOCK_SAVINGSACCOUNT', 'SAVINGSACCOUNT', 'UNLOCK',0);
You cannot edit this migration without changing the migration id, it will fail other client environments. Also, i think you should use either '0' or false. Postgre does not support integer for boolean values.

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/MON-93_permission_fd_partial_liquidation.xml
>          </addColumn>
undo formatting on migration if no code sql change has happened

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/040_add_validation_limits.xml
> +         (`grouping`,`code`,`entity_name`,`action_name`,`can_maker_checker`)
integer boolean values are not supported on postgres.

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/0032_savings_account_block_narration_history_table.xml
> +            <column name="id" type="BIGINT" >
Why is auto increment being removed from this?

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +<!--    <include file="parts/UC-24_Accrual_accounting_on_savings_account.xml" relativeToChangelogFile="true"/>-->
Why is this migration commented out?

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/application.properties
> +client.level.limit.validation.enabled=true
I think its best if you use either the ff4j feature toggle or a global configuration as opposed to having this in application properties

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/resources/application.properties
> +client.level.limit.validation.enabled=true
We can go through ff4j together if you haven't used it before

2023-02-13 19:07 UTC, Napho commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java
> +    @Column(name = "daily_withdraw_limit")
I would suggest that you keep this as a different table, maybe m_client_transaction_limit.. Only a suggestion.
The data is not important outside of withdraw operations.

2023-02-14 07:01 UTC, jumba2010 commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/MON-110_Vault_Tribe.xml
> +            INSERT INTO m_permission (grouping, code, entity_name, action_name, can_maker_checker) VALUES ('transaction_savings', 'UNLOCK_SAVINGSACCOUNT', 'SAVINGSACCOUNT', 'UNLOCK',0);
Fixed. I did this when I was testing with my local DB, then I forgot to revert

2023-02-14 07:01 UTC, jumba2010 commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/040_add_validation_limits.xml
> +         (`grouping`,`code`,`entity_name`,`action_name`,`can_maker_checker`)
Fixed

2023-02-14 07:02 UTC, jumba2010 commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/0032_savings_account_block_narration_history_table.xml
> +            <column name="id" type="BIGINT" >
Fixed. I did this when I was testing with my local DB, then I forgot to revert

2023-02-14 07:02 UTC, jumba2010 commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +<!--    <include file="parts/UC-24_Accrual_accounting_on_savings_account.xml" relativeToChangelogFile="true"/>-->
Fixed. I did this when I was testing with my local DB, then I forgot to revert

2023-02-14 07:03 UTC, jumba2010 commented on fineract-provider/src/main/resources/application.properties
> +client.level.limit.validation.enabled=true
Yes,Lets go through ff4j please, I haven't used it before

2023-02-14 07:13 UTC, jumba2010 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java
> +    @Column(name = "daily_withdraw_limit")
I Understand. Lets not do that now, as that would add extra effort and more time of reimplementing some features.

2023-02-14 07:22 UTC, Napho commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java
> +    @Column(name = "daily_withdraw_limit")
@jumba2010 please correct this if  possible, its better to take more time than deliver sub per work.

2023-02-14 07:27 UTC, jumba2010 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java
> +    @Column(name = "daily_withdraw_limit")
That's fine  @Napho . Will do that improvement then.

2023-02-17 11:11 UTC, Napho approved these changes
lgtm

2023-02-20 07:46 UTC, hero78 approved these changes
LGTM

2023-02-20 07:46 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +<!--    <include file="parts/UC-24_Accrual_accounting_on_savings_account.xml" relativeToChangelogFile="true"/>-->
Uncomment this mugration

2023-02-20 07:46 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/040_add_validation_limits.xml
> +         (`grouping`,`code`,`entity_name`,`action_name`,`can_maker_checker`)
Try such implementation 

    <changeSet author="XXXX@fiter.io" id="add_m_permission_CREATE_loan_repayment_reminder_settings">
        <preConditions onFail="MARK_RAN">
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM m_permission WHERE code = 'CREATE_loan_repayment_reminder_settings'
            </sqlCheck>
        </preConditions>
        <insert tableName="m_permission">
            <column name="grouping" value="datatable" />
            <column name="code" value="CREATE_loan_repayment_reminder_settings" />
            <column name="entity_name" value="loan_repayment_reminder_settings" />
            <column name="action_name" value="CREATE" />
            <column name="can_maker_checker" valueBoolean="true"/>
        </insert>
    </changeSet>

2023-02-20 08:38 UTC, merged